import type {NextPage} from 'next'
import Head from 'next/head'

import TabBar from '../components/TabBar/index'
import BoardTab from '../components/BoardTab/index'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Online board</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="relative flex flex-col w-full h-full">
                <TabBar />
                <BoardTab />
            </div>
        </div>
    )
}

export default Home
// "relative flex flex-column w-full h-full"
