import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'

import Sidebar from '../components/Sidebar/index'
import TabBar from '../components/TabBar/index'
import BoardTab from '../components/BoardTab/index'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Sidebar />
            <div className={styles.tabs_and_instruments_section}>
                <TabBar />
                <BoardTab />
            </div>
        </div>
    )
}

export default Home
